# docker-compose.yml
version: "3.8"

services:
  db:
    image: postgres:16
    container_name: homebrew_db
    environment:
      POSTGRES_DB: homebrewing
      POSTGRES_USER: brewmaster
      POSTGRES_PASSWORD: brewpass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U brewmaster -d homebrewing"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: homebrew_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
